### ISSUE TITLE
[Suggestion] Add color in the numbers based on the time remaining

### ISSUE THREAD

**Issue by MrBlasyMSK** [DavyCraft648/ItemLifeTime#2]
Now that you have added the time on top of the objects, I would like to make another suggestion.
It would be to add colors based on the time remaining for the object to be deleted.

-- Example:--
- Between +5 and 2 minutes could be set to light green "§a".
- Between 2 and 1 minutes it could be orange "§6".
- After 1 minute it could turn light red "§c".

This is something very "cosmetic" but it gives an original touch, I don't know if you think it's a good idea to add it, and if you think about adding it to not affect players who want to put a specific color for the time you could put it something like this:

```yml
# Show remaining time to disappear in item's nametag
display-time:
  # Set this to false if your server is lagging
  enabled: false
  # Set this to false if you want to use your own colors
  colors: true
  # Text to be set in item's nametag
  # {MINUTE}, {SECOND}, {TIME}
  # Set this to "{MINUTE}:{SECOND} {TIME}" will be shown as "01:20 01 minute" (example)
  text: "{MINUTE}:{SECOND}"
...
```
If you don't feel like doing it just close the idea, you don't have to give me reasons why you close it xd
